INSERT INTO CatalogoTiposSeguro VALUES(Seq_CatalogoTiposSeguro.nextval,'CA','Cobertura Amplia');
INSERT INTO CatalogoTiposSeguro VALUES(Seq_CatalogoTiposSeguro.nextval,'CB','Cobertura Básica');
INSERT INTO CatalogoTiposSeguro VALUES(Seq_CatalogoTiposSeguro.nextval,'CP','Cobertura Plus');

INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'AU','Audi');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'BMW','BMW');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'CHE','Chevrolet');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'DOG','Dodge');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'FRD','Ford');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'HND','Honda');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'JP','Jeep');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'MZD','Mazda');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'MB','Mercedez Benz');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'MTB','Mitsubishi');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'NSN','Nissan');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'PGT','Peugeot');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'REN','Renault');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'TYT','Toyota');
INSERT INTO CatalogoMarcas VALUES(Seq_CatalogoMarcas.nextval,'VW','Volkswagen');

INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'AV','Aveo',3);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'CR','Cruze',3);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'TSU','Tsuru',11);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'SE','Sentra',11);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'I3','i3',2);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'NEO','Neon',4);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'ECO','Ecosport',5);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'CIV','Civic',6);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'GCH','Grand Cherokee',7);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'2','2',8);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'CC','Clase C',9);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'LNC','Lancer',10);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'208','208',12);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'CL','Clio',13);
INSERT INTO CatalogoModelos VALUES(Seq_CatalogoModelos.nextval,'BTL','Beetle',14);

INSERT INTO CatalogoEstadosSiniestro VALUES(Seq_CatalogoEstadosSiniestro.nextval,'REGISTRADO','Cliente ha reportado');
INSERT INTO CatalogoEstadosSiniestro VALUES(Seq_CatalogoEstadosSiniestro.nextval,'ATENDIDO','Daños determinados');
INSERT INTO CatalogoEstadosSiniestro VALUES(Seq_CatalogoEstadosSiniestro.nextval,'EN PROCESO','Daños en reparación');
INSERT INTO CatalogoEstadosSiniestro VALUES(Seq_CatalogoEstadosSiniestro.nextval,'CONCLUIDO','Daños reparados');
INSERT INTO CatalogoEstadosSiniestro VALUES(Seq_CatalogoEstadosSiniestro.nextval,'CANCELADO','Siniestro cancelado');

INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'AGS','Aguascalientes');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'BC','Baja California');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'BCS','Baja California Sur');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'CAMP','Campeche');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'CHIS','Chiapas');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'CHIH','Chihuahua');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'COAH','Coahuila');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'COL','Colima');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'CDMX','Ciudad de México');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'DGO','Durango');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'GTO','Guanajuato');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'GRO','Guerrero');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'HGO','Hidalgo');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'JAL','Jalisco');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'MEX','México');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'MICH','Michoacán');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'MOR','Morelos');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'NAY','Nayarit');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'NL','Nuevo León');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'OAX','Oaxaca');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'PUE','Puebla');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'QRO','Querétaro');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'QROO','Quintana Roo');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'SLP','San Luis Potosí');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'SIN','Sinaloa');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'SON','Sonora');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'TAB','Tabasco');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'TAMP','Tamaulipas');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'TLAX','Tlaxcala');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'VER','Veracruz');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'YUC','Yucatán');
INSERT INTO CatalogoEstadosRepublica VALUES(Seq_CatalogoEstadosRepublica.nextval,'ZAC','Zacatecas');

