CREATE SEQUENCE Seq_Auto
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_AutoInvolucrado
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_CatalogoAgencias
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_CatalogoEstadosSiniestro
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_CatalogoEstadosRepublica
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_CatalogoMarcas
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_CatalogoModelos
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_CatalogoTiposSeguro
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_Cliente
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_Conductor
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_Cotizacion
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_EstadoSiniestro
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_HistorialEstado
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_Hospital
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_PersonaInvolucrada
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_Poliza
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_Siniestro
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;

CREATE SEQUENCE Seq_Tarjeta
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE;
